### ISSUE TITLE
Checking that all required ports are reachable for using native API for OpenStack sites

### ISSUE THREAD

**Issue by gwarf** [ARGOeu/nagios-plugins-fedcloud#33]
Related to the depreciation of OCCI, that is partly addressed by promoting the use of native OpenStack API, a campaign for opening those ports was conducted.
Here is the list of those ports: https://egi-federated-cloud-integration.readthedocs.io/en/latest/openstack.html#open-ports

Port | Application | Note
------------ | ------------- | ------------- 
5000/TCP | OpenStack/Keystone |  Authentication to your OpenStack.
8776/TCP | OpenStack/cinder | Block Storage management.
8774/TCP | OpenStack/nova | VM management.
9696/TCP | OpenStack/neutron | Network management.
9292/TCP | OpenStack/glance | VM Image management.
2170/TCP | BDII/LDAP | EGI Service Discovery/Information System.
8787/TCP | OpenStack/ooi | EGI EGI Virtual Machine Management (optional).

Some services may have been changed to listen on different ports, but as all those services should be discoverable from Keystone this shouldn't be a problem. Keystone endpoint is the one that is expected to be found in the GOCDB.

So either the existing probe need to be updated to control that those services are available, or we should had one or more new probes to control this.

**Comment by kkoumantaros** [comment]
@gwarf  this is not a issue with the current probe but a feature request for a new one, please follow the established procedure.

**Comment by gwarf** [comment]
The goal was to start discussing this, with @enolfc we were discussing that we may be able to make a PR for updating the Nova probe that is in this repository.
