### ISSUE TITLE
OpenStack sites without a default network fail the probe

### ISSUE THREAD

**Issue by enolfc** [ARGOeu/nagios-plugins-fedcloud#45]
Sites such as RECAS-Bari require the user to specify a network when creating a server otherwise the command fails with:

```
Conflict: Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-41ae38ea-7386-426e-9082-891df3499c36)
````

Available networks should be discovered and select one of them for the VM creation

**Comment by vrdel** [comment]
Resolved in #46
